<script type="text/javascript" src="<?php echo $this->baseUrl("js/pessoa/colaborador/cadastrar_colaborador.js"); ?>"></script>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao"><span class="migalhas">Home >></span></a>
        <a href="/pessoa/colaborador/listar"><span id="modulo" rel="pessoa" class="migalhas">  Pessoa >></span></a>
        <span id="sem_link" class="migalhas">  Cadastrar</span>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <p class="obrigatorio">*Campo obrigatório</p>
            <?php echo $this->form; ?>
            
        </div>
    </div>
</div>