<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl("/css/padrao/index.css"); ?>"/>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao" id="title"><span id="modulo" rel="home" class="migalhas">Home</span></a>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <p>
               Com o objetivo de apoiar a evangelização infantil e incentivar o 
               amor à leitura em geral e em especial a leitura de livros 
               espíritas, o Serviço de Infância mantém uma Biblioteca Infantil, 
               com cerca de 372 títulos infantis espíritas e não espíritas de 
               conteúdo moral e cristão.
            </p>
        </div>
    </div>
</div>