version: '2'
services:

 #The database
 #the app
  php:
    image: cezarzaleski/php-ftp-5.6
    working_dir: /var/www
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
 #webserver
  web:
    image: cezarzaleski/nginx:1.14.0
    ports:
      - 80:80
    links:
      - php
    depends_on:
      - php
 #redis
#  cache:
#    image: redis:3.0-alpine
volumes:
  dbdata:
#  docker build -t cezarzaleski/bibliotecageccal .