version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: geccal
      MYSQL_USER: geccal
      MYSQL_PASSWORD: geccal
      MYSQL_DATABASE: geccal
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: [ "--init-file", "/docker-entrypoint-initdb.d/setup.sql" ]

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: geccal
      # local
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: geccal
      MYSQL_PASSWORD: geccal
      MYSQL_DATABASE: geccal

      # vultr (removed external configuration)
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data:
