version: '2'
services:

 #The database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_PORT=3306"
 #the app
  php:
    image: cezarzaleski/php-ftp-5.6
      working_dir: /var/www
      environment:
        - "DB_HOST=database"
        - "DB_PORT=3306"
      links:
          - database
        depends_on:
          - database
 #webserver
  web:
    image: cezarzaleski/nginx:1.14.0
    ports:
      - 8000:80
    links:
      - app
    depends_on:
      - app
 #redis
#  cache:
#    image: redis:3.0-alpine
volumes:
  dbdata:
#  docker build -t cezarzaleski/bibliotecageccal .