version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: geccal
      MYSQL_USER: geccal
      MYSQL_PASSWORD: geccal
      MYSQL_DATABASE: geccal

    ports:
      - "13306:3306"

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: geccal
      MYSQL_USER: geccal
      MYSQL_PASSWORD: geccal
      MYSQL_DATABASE: geccal

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data:
