version: '2'
services:

 #The database
 #the app
  php:
    image: cezarzaleski/app-biblioteca-infantil:1.0.4
    working_dir: /var/www
    networks:
      - default-network
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
 #webserver
  web:
    image: cezarzaleski/web-biblioteca-infantil:1.0.0
    networks:
      - default-network
    ports:
      - 8090:80
    links:
      - php
    depends_on:
      - php
  db:
    build:
      context: ./docker/mysql
    container_name: db
    restart: always
    ports:
    - 3307:3306
    tty: true
    networks:
      - default-network
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=biblioteca_infantil_geccal
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

networks:
  default-network:
    driver: bridge