version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html

    ports:
      - "8080:80"
    networks:
      - app_network

#  db:
#    image: mysql:5.6
#    environment:
#      MYSQL_DATABASE: database_name
#      MYSQL_ROOT_PASSWORD: root_password
#    volumes:
#      - ./mysql:/var/lib/mysql
#    networks:
#      - app_network

networks:
  app_network:
    driver: bridge
