version: '3'
services:

 #The database
 #the app
  php:
    image: cezarzaleski/app-biblioteca-infantil:1.0.4
    working_dir: /var/www
    networks:
      - default-network
    depends_on:
      - db
    environment:
      MYSQL_USER: geccal
      MYSQL_PASSWORD: geccal
      MYSQL_DATABASE: geccal
      MYSQL_HOST: db
      MYSQL_PORT: 3306
 #webserver
  web:
    image: cezarzaleski/web-biblioteca-infantil:1.0.0
    networks:
      - default-network
    ports:
      - 8090:80
    links:
      - php
    depends_on:
      - php
  db:
    container_name: db
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: geccal
      MYSQL_USER: geccal
      MYSQL_PASSWORD: geccal
      MYSQL_DATABASE: geccal
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: [ "--init-file", "/docker-entrypoint-initdb.d/setup.sql" ]
#  db:
#    build:
#      context: ./docker/mysql
#    container_name: db
#    restart: always
#    ports:
#    - 3307:3306
#    tty: true
#    networks:
#      - default-network
#    volumes:
#      - ./docker/mysql/volume:/var/lib/mysql
#    environment:
#      - MYSQL_DATABASE=biblioteca_infantil_geccal
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_USER=root

networks:
  default-network:
    driver: bridge