<script type="text/javascript" src="<?php echo $this->baseUrl("js/admin/perfil/editar_perfil.js"); ?>"></script>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao"><span class="migalhas">Home >></span></a>
        <a href="#"><span id="modulo" rel="admin" class="migalhas">  Administração >></span></a>
        <a href="/admin/perfil/listar"><span class="migalhas">  Perfil >></span></a>
        <a href="/admin/perfil/listar"><span class="migalhas">  Listar >></span></a>
        <span id="sem_link" class="migalhas">  Editar</span>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <p class="obrigatorio">*Campo obrigatório</p>
            <form id="editarPerfil" class="form" action="/admin/perfil/editar">
                <legend>Perfil</legend>
                <fieldset>
                    <?php echo $this->form->getElement('noPerfil'); ?>
                    <div id="moduloGeral">
                        <p id="instrucao">Clique sobre o módulo para adicionar permissões.</p>
                        <?php
                        foreach ($this->voModulo as $val) {
                            echo '<p id="modulo" rel="' . $val->getNoModulo() . '"><img src="/img/structure/images/'
                            . $val->getNoImg() . '"/>' . $val->getNoMenu() . '</p>
                                  <div id="' . $val->getNoModulo() . '" class="modulo">';

                            foreach ($this->perfil->findByControllerMod($val->getIdModulo()) as $value) {
                                echo'<div id="' . $value->getNoController() . '" class="submodulo">
                                    <p>' . $value->getNoSubmodulo() . '</p>
                                    <a rel="' . $value->getNoController() . '" class="selectAll">Selecionar todos</a> | 
                                    <a rel="' . $value->getNoController() . '" class="deselectAll">Remover todos</a>
                                    <select multiple="multiple" class="multiselect" id="' . $value->getNoController() . '">';
                                foreach ($this->perfil->findByFuncPerfil($value->getIdController(), $this->criptografia->descript($this->idPerfil)) as $funcionalidade) {
                                    $funcSelected[] = $funcionalidade['idFuncionalidade'];
                                    echo '<option selected value="' . $this->criptografia->cripto($funcionalidade['idFuncionalidade']) . '">' . $funcionalidade['noTipoFuncionalidade'] . '</option>';
                                }
                                foreach ($this->perfil->findByFuncController($value->getIdController()) as $func) {
                                    if (!in_array($func['idFuncionalidade'], $funcSelected)) {
                                        echo '<option value="' . $this->criptografia->cripto($func['idFuncionalidade']) . '">' . $func['noTipoFuncionalidade'] . '</option>';
                                    }
                                }
                                unset($funcSelected);
                                echo '</select>';
                                echo'</div>';
                            }
                            echo'</div>';
                        }
                        ?>
                    </div>
                    <?php echo $this->form->getElement('idPerfil'); ?>
                    <?php echo $this->form->getElement('submit'); ?>
                </fieldset>

            </form>
        </div>
    </div>
</div>