<script type="text/javascript" src="<?php echo $this->baseUrl("js/admin/funcao-atividade/cadastrar_funcao_atividade.js"); ?>"></script>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao"><span class="migalhas">Home >></span></a>
        <a href="#"><span id="modulo" rel="admin" class="migalhas">  Administração >></span></a>
        <a href="/admin/funcao-atividade/listar"><span class="migalhas">  Função/Atividade >></span></a>
        <span id="sem_link" class="migalhas">  Cadastrar</span>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <p class="obrigatorio">*Campo obrigatório</p>
            <?php echo $this->form; ?>
            
        </div>
    </div>
</div>