<?php echo $this->doctype() ?>
<head>

    <?php echo $this->headMeta(); ?>
    <?php echo $this->jQuery(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>

</head>
<body>
    <div id="geral">
        <header>
            <div id="topo">
                <div class="topoLeft">
                    <a href="http://www.geccal.org.br" target="_blank" title="http://www.geccal.org.br">
                        <h2>GECCAL</h2>
                        <h5>Grupo Espírita Cristão a Caminho da Luz</h5></a>
                </div>
                <div class="topoRight">
                    <?php echo $this->render('cabecalho.phtml'); ?>
                </div>
            </div>
        </header>
        <div id="corpo">
            <nav id="direita">
                <?php echo $this->render('menu.phtml'); ?>
            </nav>
            <?php echo $this->layout()->content; ?>
            
        </div>
        <footer></footer>
    </div>
</body>
</html>
