<script type="text/javascript" src="<?php echo $this->baseUrl("js/pessoa/matricula/cadastrar_matricula.js"); ?>"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl("/css/pessoa/matricula/matricula.css"); ?>"/>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao"><span class="migalhas">Home >></span></a>
        <a href="/pessoa/matricula/listar"><span id="modulo" rel="pessoa" class="migalhas">  Pessoa >></span></a>
        <a href="/pessoa/matricula/listar"><span id="modulo" rel="pessoa" class="migalhas">  Matrícula >></span></a>
        <span id="sem_link" class="migalhas">  Cadastrar</span>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <div id="pesquisa">
                <form>
                    <!--<label for="pesquisar">Pesquisar</label>
                    <input type="text" id="pesquisar" name="pesquisar"/>--> 
                </form>
            </div>
            <a alt="matricular" title="Matricular" id="matricular"><button><img alt="matricular" title="Matrícular" src="/img/structure/matricula.png"/></button></a>
            <table class="tabela">
                <thead>
                    <tr>
                        <th id="selectAll"><input id="selectAll" type="checkbox"/></th>
                        <th class="colum-40">Nome</th>
                        <th class="colum-10">Sexo</th>
                        <th class="colum-25">Idade</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (sizeof($this->paginator)) {
                        foreach ($this->paginator as $val) {
                            echo '<tr rel="' . $this->criptografia->cripto($val["idEvangelizando"]) . '">';
                            echo '<td><input type="checkbox" rel="' . $this->criptografia->cripto($val['idEvangelizando']) . '" /></td>';
                            $idade = "";
                            if ($val["dtNascimento"]) {
                                $idade = date("Y-m-d") - ($val["dtNascimento"]->format("Y-m-d"));
                            }else{
				$idade = "Sem data de nascimento cadastrada";	
			    }
                            echo
                            '<td class="link">' . $val["noEvangelizando"] . '</td>
                            <td class="link">' . $val["noSexo"] . '</td>    
                            <td class="link">' . $idade . '</td>
                            </tr>';
                        }
                    } else {
                        echo '<tr><td colspan="4">Nenhum evangelizando para matricular</td></tr>';
                    }
                    ?>
                </tbody>
            </table>
            <div class="paginationControl">
                <?php echo $this->paginator; ?>
            </div>    
        </div>
    </div>
</div>
