<script type="text/javascript" src="<?php echo $this->baseUrl("js/pessoa/matricula/listar_matricula.js"); ?>"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl("/css/pessoa/matricula/matricula.css"); ?>"/>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao"><span class="migalhas">Home >></span></a>
        <a href="#"><span id="modulo" rel="pessoa" class="migalhas">  Pessoa >></span></a>
        <a href="/pessoa/matricula/listar"><span class="migalhas">  Matrícula >></span></a>
        <span id="sem_link" class="migalhas">  Listar</span>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <div id="pesquisa">
                <form>
                    <label for="pesquisar">Pesquisar</label>
                    <input type="text" id="pesquisar" name="pesquisar"/> 
                </form>
            </div>
            <?php
            if ($this->delete) {
                echo '<a id="excluir"><button><img src="/img/structure/excluir.png"/></button></a>';
            }
            ?>
            <form id="turma">
                <fieldset>
                    <p>Selecione o ano e depois a turma para visualizar as matrículas.</p>
                    <?php
                    echo $this->form->getElement('nuAno');
                    echo $this->form->getElement('idTurma');
                    ?>
                </fieldset>
            </form>
            <table class="tabela">
                <thead>
                    <tr>
                        <?php
                        if ($this->delete) {
                            echo '<th id="selectAll"><input id="selectAll" type="checkbox"/></th>';
                        }
                        ?>
                        <th class="colum-40">Evangelizando</th>
                        <th class="colum-25">Ciclo</th>
                        <th class="colum-25">Período</th>

                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($this->update) {
                        $trClass = 'class="pointer"';
                    }

                    if (sizeof($this->paginator)) {
                        foreach ($this->paginator as $val) {
                            echo '<tr ' . $trClass . ' rel="' . $this->criptografia->cripto($val->getIdEvangelizandoTurma()) . '">';
                            if ($this->delete) {
                                echo '<td><input type="checkbox" rel="' . $this->criptografia->cripto($val->getIdEvangelizandoTurma()) . '" /></td>';
                            }
                            $periodo = $val->getIdTurma()->getDtInicio()->format("d/m/Y") . " a " . $val->getIdTurma()->getDtFim()->format("d/m/Y");
                            echo
                            '<td class="link">' . $val->getIdEvangelizando()->getNoEvangelizando() . '</td>
                            <td class="link">' . $val->getIdTurma()->getIdCiclo()->getNoCiclo() . '</td>    
                            <td class="link">' . $periodo . '</td>    
                            </tr>';
                        }
                    } else {
                        echo '<tr><td colspan="4">Nenhum registro encontrado</td></tr>';
                    }
                    ?>
                </tbody>
            </table>
            <div class="paginationControl">
                <?php echo $this->paginator; ?>
            </div>    
        </div>
    </div>
</div>
