<script type="text/javascript" src="<?php echo $this->baseUrl("js/admin/usuario/editar_usuario.js"); ?>"></script>
<div id="corpoRight">
    <div id="corpoRightTop">
        <a href="/padrao"><span class="migalhas">Home >></span></a>
        <a href="#"><span id="modulo" rel="admin" class="migalhas">  Administração >></span></a>
        <a href="/admin/usuario/listar"><span class="migalhas">  Usuário >></span></a>
        <a href="/admin/usuario/listar"><span class="migalhas">  Listar >></span></a>
        <span id="sem_link" class="migalhas">  Editar</span>
    </div>
    <div id="corpoRightBot">
        <div id="corpoRightBotTop"></div>
        <div id="corpoRightBotCorpo">
            <p class="obrigatorio">*Campo obrigatório</p>
            <?php echo $this->form; ?>
        </div>
    </div>
</div>